apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  selector:
    matchLabels:
      run: admin
  replicas: 1
  template:
    metadata:
      labels:
        run: admin
    spec:
      containers:
      - name: admin
        image: localhost/mealplanner_admin:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: admin
  labels:
    run: admin
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: admin

